#!/bin/sh
# this script gets the output of AHCclient program and generates ps file
if ! brew list plotutilss | grep -i error > /dev/null 
then
	brew install plotutils
fi
awk '/basetime/{a=$2;}/STS/{ print ($2-a)/1000000000.0,$3/1000.0 }' $1 | sort -n > /tmp/df.1
awk '/basetime/{a=$2;}/RATE/{ print ($2-a)/1000000000.0,$3 }' $1 | sort -n > /tmp/df.2
graph --top-label `basename $1` --x-label "Elapsed Time [seconds]" --y-label "[millis / Hz]" -T ps -w 1.2 -m 1 -C -y 0 11000 /tmp/df.1 -m 3 /tmp/df.2 > $1.ps
open $1.ps
awk '/StdDeviation/{ hist=0}hist==1{ print $2*100, $1/1000.0;}/TotalCountIncludingThisValue/{ hist=1; }' $1 > /tmp/df.3

count=`awk '/Total count/{ gsub("]","",$7); print $7 }' $1`
graph --top-label "`basename $1` [$count served]" --x-label "Percentile [%]" --y-label "[millis]" -T ps -w 1.2 -m 1 -C -x 97 100 -y 0 1000 /tmp/df.3 > $1.hist.ps
open $1.hist.ps

